### PR TITLE
Drafting the initial use cases and functional requirements for managing geospatial metadata

### PR DESCRIPTION
**Pull request by jrgriffiniii**

### CODE REVIEW

**Comment by no-reply** [comment]
Awesome! is this group following http://www.w3.org/2015/spatial/wiki/Main_Page ?

It would be nice to keep aware of the relationship between your use cases and goals and those of the W3C group.

**Comment by jrgriffiniii** [comment]
@no-reply I'm uncertain as to the standing of the group in relation to these standards, but regardless, I'm fairly certain that all interested parties would benefit from me restructuring these use cases in accordance with these guidelines.

My apologies for this oversight, thank you for this guidance.

**Comment by eliotjordan** [comment]
@jrgriffiniii I'm looking at these use cases again, and I notice that they really straddle the line between discovery (GeoBlacklight) and preservation (Hydra) layers. Many of the searching and faceting requirements belong in the discovery layer, for example. However, [controlled vocabulary](https://github.com/projecthydra-labs/curation_concerns/blob/14ec5ab19054f8a00e151a109201c7e9c680aaa7/curation_concerns-models/app/models/concerns/curation_concerns/with_basic_metadata.rb#L82-L84) functionality for place and theme etc... could be important in the preservation system. Also, incorporating point of contact data into GeoBlacklight would be a nice feature; especially in a federated system.

**Comment by jrgriffiniii** [comment]
> @jrgriffiniii I'm looking at these use cases again, and I notice that they really straddle the line between discovery (GeoBlacklight) and preservation (Hydra) layers.

@eliotjordan my apologies for the delay in my contributions regarding these.  Throughout early next week I should be in the position to publish the rescoped and refined use cases.

> However, controlled vocabulary functionality for place and theme etc... could be important in the preservation system.

Agreed, thank you greatly for this suggestion.

I'll be certain to evaluate several ontologies or generalized controlled vocabularies before a second pull request is issued.

**Pull request merged**
