### PR TITLE
add GeoreferencedBehavior for behaviors common to georeferenced/geore…

### PR DESCRIPTION
**Pull request by drh-stanford**
inserts an georeferenced behavior since the BasicGeoMetadata is too low a level to require a CRS

### CODE REVIEW

**Comment by eliotjordan** [comment]
This makes sense. Was trying to sketch these out quickly. What do you think about the RDF URIs for these? As this is somewhat uncharted territory, we're going to have to have make it up as we go for the most part (with outside input, of course).

**Comment by drh-stanford** [comment]
maybe `http://projecthydra-labs/pcdm-geo-models#xxx` -- I don't think the URI has to actually be a working URL

**Comment by eliotjordan** [comment]
I suppose ```http://projecthydra-labs/pcdm-geo-models#xxx``` looks cleaner. However, "http://www.georss.org/georss/box" seems pretty clear and is the suggested RDF URI according to georss.org. crsURI is pretty well defined by OGC. Envelope is a bit tricky. It was hard to pin down exactly where that syntax (used by SOLR) is defined. As far as  I can tell, it came from the CSW spec. We may not actually need :solr_geom, so that may not be an issue.

**Comment by drh-stanford** [comment]
Yeah, anything that has a URI already we should use -- the hydra URI is only for new things we're defining for this model

**Comment by eliotjordan** [comment]
Looks good to me. I'll merge unless you want to add anything else.

**Comment by drh-stanford** [comment]
nope, i'm ok with merging both

**Pull request merged**
